#:schema node_modules/wrangler/config-schema.json
name = "talk-to-javascript"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"


[dev]
live_reload = true